insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
16,'ISSQN NFe Saída','A',sysdate,'jlsilva',10,'N','C','N','S','N','ISS','N','A','R','R','S','S',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','S',null,null,'S','N','S','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
2,'***IPI','A',sysdate,'jlsilva',6,'S','I','I','S','N','IPI','N','A','V','V','N','N',null,null,null,null,'N',null,'S','N','Estab','N',null,null,'S','N','S',null,'S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
11,'PIS (Cooperativa)','A',sysdate,'jlsilva',13,'D','C','N','N','S','PIS','S','PJ','V','V','S','S',null,null,null,null,'N',06,'S','N','Estab','N',null,null,'S','N','S','N','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
12,'COFINS (Cooperativa)','A',sysdate,'jlsilva',13,'D','C','N','N','S','COFINS','S','PJ','V','V','S','S',null,null,null,null,'N',null,'S','N','Estab','N',null,null,'S','N','S',null,'S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
14,'Retenção CSLL (Fatura Emitida)','A',sysdate,'jlsilva',15,'D','C','N','N','S','CSLL','N','PJ','R','R','S','S',null,null,null,null,'N',null,'S','N','Estab','N',null,null,'S','N','S','N','S',null,'N',null,'N','S',null,'N',1161,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
557,'ISS Retido de Terceiros - Jales','A',sysdate,'jlsilva',10,'D','C','N','N','S','ISS','S','A','R','E','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','S','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
558,'ISS Retido de Terceiros - Mirassol','A',sysdate,'jlsilva',10,'D','C','N','N','S','ISS','S','A','R','E','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','S','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
559,'ISS Retido de Terceiros - Olimpia','A',sysdate,'jlsilva',10,'D','C','N','N','S','ISS','S','A','R','E','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','S','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
503,'Prod. Méd. - INSS por Proventos de RH','A',sysdate,'jlsilva',11,'D','C','N','S','S','INSS','S','PF','V','V','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','S','S','S',null,'N',1,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
507,'INSS Retido de Terceiros','A',sysdate,'jlsilva',11,'D','C','N','S','S','INSS','S','A','C','E','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','S','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
502,'IRRF Retido de Terceiros','A',sysdate,'jlsilva',12,'D','C','N','N','S','IR','S','A','V','E','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','S',null,null,'S','N','S','N','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
520,'ISS Retido Terceiros-SJRP e Cooperados','A',sysdate,'jlsilva',10,'D','C','N','N','S','ISS','S','A','R','V','N','N',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','N',null,null,'S','N','N','S','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
3,'PIS/Cofins/CSLL Retido de Terceiros','A',sysdate,'jlsilva',13,'D','C','N','N','S','PISCOFINSCSLL','S','PJ','V','V','S','S',null,sysdate,'jlsilva',null,'N',null,'S','N','Estab','S',null,null,'S','N','S','N','S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);

insert into tributo (
CD_TRIBUTO,DS_TRIBUTO,IE_SITUACAO,DT_ATUALIZACAO,NM_USUARIO,CD_TIPO_VALOR,IE_SOMA_DIMINUI,IE_CORPO_ITEM,IE_CENTRO_CUSTO,IE_RATEIO,IE_CONTA_PAGAR,IE_TIPO_TRIBUTO,IE_GERAR_TITULO_PAGAR,
IE_PF_PJ,IE_VENCIMENTO,IE_VENC_NF,IE_GERAR_TRIB_NF,IE_APURACAO_PISO,NR_SEQ_TRANS_REC,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,NR_SEQ_TRANS_IMP,IE_REPASSE_TITULO,IE_GRUPO_TRIBUTO,
IE_ATUALIZAR_VENC_TRIB,IE_BAIXA_TITULO,IE_CNPJ,IE_NF_TIT_REC,NR_SEQ_TRANS_TIT_REC,IE_DT_CONTAB_TIT_TRIB,IE_ACUMULAR_TRIB_LIQ,IE_SOMENTE_NF,IE_CCM,IE_SUPER_SIMPLES,IE_SALDO_TIT_PAGAR,
CD_CONTA_FINANC,IE_FORMA_ARRED_NF,CD_ESTABELECIMENTO,IE_INCIDE_CONTA,IE_RESTRINGE_ESTAB,NR_TRIBUTACAO_MUNICIPIO,IE_DESC_NF,NR_SEQ_TRANS_PROV_TRIB_REC,IE_VENC_REPASSE,NR_SEQ_TRANS_CONV_REC,
IE_FORMA_ARRED_OPS,IE_RESTRINGE_EMPRESA,IE_GERA_NF_DEVOLUCAO,IE_GERAR_TRIB_NFSE,IE_ATUALIZAR_TRIB_LIQ,IE_REGRA_PF_SOBRE_CP,IE_VALOR_BASE_TITULO_NF,CD_RETENCAO,IE_CONTAB_PROV_CP,IE_RATEIO_CLASSIF,
IE_DATA_IRPF,IE_ISENTO,IE_VENC_PLS_PAG_PROD,IE_CONSIDERA_VALOR_PF,IE_DESC_DESP_CARTAO
) values (
564,'CSLL (Cooperativa)','A',sysdate,'jlsilva',13,'D','C','N','N','S','CSLL','S','PJ','V','V','S','S',null,null,null,null,'N',null,'S','N','Estab','N',null,null,'S','N','S',null,'S',null,'N',null,'N','S',null,'N',null,'N',null,'N','N','N','S','N','N','N',null,'N','S','A','N',null,'N','S'
);