insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
380,1,507,sysdate,'jlsilva',46379400000150,11.0000,3812,null,null,null,null,null,0.01,0.00,'S',3916.20,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','N',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
382,1,507,sysdate,'jlsilva',46379400000150,20.0000,3812,null,null,null,null,null,0.01,0.00,'S',3916.20,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','N',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2778,1,507,sysdate,'jlsilva',46379400000150,11.0000,3812,null,null,null,null,null,0.01,0.00,'S',3916.20,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','N',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2779,1,507,sysdate,'jlsilva',46379400000150,11.0000,3812,null,null,null,null,null,0.01,0.00,'S',3916.20,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','N',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2780,1,507,sysdate,'jlsilva',46379400000150,11.0000,3812,null,null,null,null,null,0.01,0.00,'S',3916.20,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','N',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3851,1,507,sysdate,'jlsilva',46379400000150,20.0000,3812,null,null,null,null,null,0.01,0.00,'S',5189.82,sysdate,'jlsilva',0.00,null,'** TRIBUTO CADASTRADO PARA GERAR INSS DOS EVENTOS MANUAIS DE PRODUÇÃO MEDICA. (EXEMPLO EVENTO 319- PLANTOES PAI)',to_date('01/01/2016', 'dd/mm/yyyy'),null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3852,1,507,sysdate,'jlsilva',46379400000150,20.0000,3812,null,null,null,null,null,0.01,0.00,'S',5189.82,sysdate,'jlsilva',0.00,null,null,to_date('01/01/2016', 'dd/mm/yyyy'),null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3853,1,507,sysdate,'jlsilva',46379400000150,20.0000,3812,null,null,null,null,null,0.01,0.00,'S',5189.82,sysdate,'jlsilva',0.00,null,null,to_date('01/01/2016', 'dd/mm/yyyy'),null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3854,1,507,sysdate,'jlsilva',46379400000150,20.0000,3812,null,null,null,null,null,0.01,0.00,'S',5189.82,sysdate,'jlsilva',0.00,null,null,to_date('01/01/2016', 'dd/mm/yyyy'),null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3856,1,507,sysdate,'jlsilva',46379400000150,20.0000,null,null,null,null,null,null,0.01,0.00,'S',5189.82,sysdate,'jlsilva',0.00,null,null,to_date('01/01/2016', 'dd/mm/yyyy'),null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
3124,null,502,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.01,10.00,'S',0.00,sysdate,'jlsilva',0.00,1708,null,null,null,'J',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,3,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
388,1,502,sysdate,'jlsilva',46379400000150,1.0000,3812,null,null,null,null,null,0.01,0.01,'S',0.00,sysdate,'jlsilva',0.00,0588,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
261,null,520,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.00,0.00,'N',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'J',null,null,'N',null,353030,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','A',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
400,1,520,sysdate,'jlsilva',46379400000150,2.0100,3812,null,null,null,null,null,0.01,0.01,'N',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'F',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','S',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2805,null,520,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.00,0.00,'N',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'J',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','A',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2839,null,520,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.00,0.00,'N',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'J',null,null,'N',null,353030,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','A',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2840,null,520,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.00,0.00,'N',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'J',null,null,'N',null,353030,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','A',null,null,0.00,'N',null,null
);

insert into TRIBUTO_CONTA_PAGAR (
NR_SEQUENCIA,CD_ESTABELECIMENTO,CD_TRIBUTO,DT_ATUALIZACAO,NM_USUARIO,CD_BENEFICIARIO,PR_ALIQUOTA,CD_CONTA_FINANC,CD_PESSOA_JURIDICA,CD_COND_PAGTO,NR_SEQ_TRANS_REG,CD_PESSOA_FISICA,
NR_SEQ_TRANS_BAIXA,VL_MINIMO,VL_MINIMO_TRIBUTO,IE_ACUMULATIVO,VL_TETO_BASE_CALCULO,DT_ATUALIZACAO_NREC,NM_USUARIO_NREC,VL_DESC_DEPENDENTE,CD_DARF,DS_OBSERVACAO,DT_INICIO_VIGENCIA,
DT_FIM_VIGENCIA,IE_TIPO_PESSOA,NR_SEQ_TRANS_REG_REP,NR_SEQ_TRANS_BAIXA_REP,IE_CONTAB_VALOR_TRIB,CD_NATUREZA_OPERACAO,CD_MUNICIPIO_IBGE,CD_EMPRESA,CD_TIPO_SERVICO,CD_MATERIAL,CD_GRUPO_MATERIAL,
CD_SUBGRUPO_MATERIAL,CD_CLASSE_MATERIAL,IE_TIPO_CONTRATACAO,IE_FILANTROPIA,NR_SEQ_TIPO_REPASSE,CD_OPERACAO_NF,CD_TIPO_PESSOA_JUR,IE_MAT_REPASSE,IE_TRIB_PAGO,NR_SEQ_CLASSE_TP,CD_TIPO_BAIXA_NEG,
NR_SEQ_CNAE,NR_SEQ_NAT_JURIDICA,PR_BASE_CALCULO,IE_TIPO_TRIBUTACAO,VL_BASE_INICIAL,VL_BASE_FINAL,IE_TIPO_TRIB_MUNICIPAL,IE_ESTRUT_MAT_NF,IE_PRODUCAO_MEDICA,NR_SEQ_CLASSE,SG_ESTADO,PR_REDUCAO_BASE,
IE_TITULO_SEM_MATERIAL,IE_ORIGEM_TITULO,NR_SEQ_TIPO_PRESTADOR)
values (
2864,1,520,sysdate,'jlsilva',46379400000150,0.0000,3812,null,null,null,null,null,0.01,0.00,'S',0.00,sysdate,'jlsilva',0.00,null,null,null,null,'A',null,null,'N',null,null,1,null,null,null,null,null,null,'N',null,null,null,'S','T',null,null,null,null,null,null,null,null,null,'N','A',null,null,0.00,'N',null,null
);